language: python
python:
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n env
  - conda activate env
  - conda install -c conda-forge pygraphblas 
  - pip install -r req.txt
script:
  - pytest -s src/tests.py
